-- MySQL Script generated by MySQL Workbench
-- Sun Sep  3 12:41:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Dish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dish` ;

CREATE TABLE IF NOT EXISTS `Dish` (
  `idDish` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `categories` VARCHAR(45) NULL,
  `price` INT NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`idDish`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Users` ;

CREATE TABLE IF NOT EXISTS `Users` (
  `idUser` INT NOT NULL,
  `lastName` VARCHAR(45) NULL,
  `firstName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `soldeCarteCrous` DOUBLE NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Command`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Command` ;

CREATE TABLE IF NOT EXISTS `Command` (
  `idCommand` INT NOT NULL,
  `orderDate` DATETIME NULL,
  `deliveryAdress` VARCHAR(45) NULL,
  `dueDate` DATETIME NULL,
  `orderStatus` VARCHAR(45) NULL,
  `duration` VARCHAR(45) NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idCommand`, `idUser`),
  INDEX `fk_Commande_Users1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Commande_Users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Allergen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Allergen` ;

CREATE TABLE IF NOT EXISTS `Allergen` (
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ingredient` ;

CREATE TABLE IF NOT EXISTS `Ingredient` (
  `idIngredient` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `calorie` VARCHAR(45) NULL,
  `Allergen_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idIngredient`, `Allergen_name`),
  INDEX `fk_Ingredient_Allergen1_idx` (`Allergen_name` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredient_Allergen1`
    FOREIGN KEY (`Allergen_name`)
    REFERENCES `Allergen` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Compose`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Compose` ;

CREATE TABLE IF NOT EXISTS `Compose` (
  `idDish` INT NOT NULL,
  `idCommand` INT NOT NULL,
  `quantity` INT NULL,
  `totalAmount` DECIMAL(2) NULL,
  PRIMARY KEY (`idDish`, `idCommand`),
  INDEX `fk_Dish_has_Commande_Commande1_idx` (`idCommand` ASC) VISIBLE,
  INDEX `fk_Dish_has_Commande_Dish_idx` (`idDish` ASC) VISIBLE,
  CONSTRAINT `fk_Dish_has_Commande_Dish`
    FOREIGN KEY (`idDish`)
    REFERENCES `Dish` (`idDish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dish_has_Commande_Commande1`
    FOREIGN KEY (`idCommand`)
    REFERENCES `Command` (`idCommand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Contain` ;

CREATE TABLE IF NOT EXISTS `Contain` (
  `idIngredient` INT NOT NULL,
  `idDish` INT NOT NULL,
  PRIMARY KEY (`idIngredient`, `idDish`),
  INDEX `fk_Ingredient_has_Dish_Dish1_idx` (`idDish` ASC) VISIBLE,
  INDEX `fk_Ingredient_has_Dish_Ingredient1_idx` (`idIngredient` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredient_has_Dish_Ingredient1`
    FOREIGN KEY (`idIngredient`)
    REFERENCES `Ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredient_has_Dish_Dish1`
    FOREIGN KEY (`idDish`)
    REFERENCES `Dish` (`idDish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Favorites` ;

CREATE TABLE IF NOT EXISTS `Favorites` (
  `Dish_idDish` INT NOT NULL,
  `idUser` INT NOT NULL,
  `favorite` TINYINT NULL,
  PRIMARY KEY (`Dish_idDish`, `idUser`),
  INDEX `fk_Dish_has_Users_Users1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_Dish_has_Users_Dish1_idx` (`Dish_idDish` ASC) VISIBLE,
  CONSTRAINT `fk_Dish_has_Users_Dish1`
    FOREIGN KEY (`Dish_idDish`)
    REFERENCES `Dish` (`idDish`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dish_has_Users_Users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)!
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


